#!/usr/bin/python

import wave
import time

from usbtmc import UsbTMC
from time import strftime, localtime

scope = UsbTMC("/dev/usbtmc2")

# Grab the raw data from channel 1
scope.write(":STOP")
scope.write(":WAV:POIN:MODE RAW")

rawdata = scope.ask(":WAV:DATA? CHAN1")[10:]
data_size = len(rawdata)
sample_rate = scope.ask_for_values(':ACQ:SAMP?')[0]

print 'Data size:', data_size, "Sample rate:", sample_rate
scope.write(":KEY:FORCE")
scope.close()

# Dump data to the wav file
suff = strftime("%Y-%m-%d %H.%M.%S", localtime())

wav_file = wave.open("out/channel1-" + suff + ".wav", "w")
nchannels = 1
sampwidth = 1
comptype = "NONE"
compname = "not compressed"

wav_file.setparams((nchannels, sampwidth, sample_rate, data_size, comptype, compname))
wav_file.writeframes(rawdata)
wav_file.close()
