#!/usr/bin/python

from akrigol import *

tmc = UsbTMC()

def blahblah():
    print_sep()
    print(make_timestamp())
    print("")
    tmc.ask_and_print_float("Maximum (peak)", ":MEASure:VMAX?", "", as_volt)
    tmc.ask_and_print_float("Minimum (peak)", ":MEASure:VMIN?", "", as_volt)
    tmc.ask_and_print_float("Peak-to-peak (Max - Min)", ":MEASure:VPP?", "", as_volt)
    print("")
    tmc.ask_and_print_float("Top (avg max)", ":MEASure:VTOP?", "", as_volt)
    tmc.ask_and_print_float("Base (avg min)", ":MEASure:VBAS?", "", as_volt)
    tmc.ask_and_print_float("Amplitude (Top - Base)", ":MEASure:VAMPlitude?", "", as_volt)
    print("")
    tmc.ask_and_print_float("Average", ":MEASure:VAV?", "", as_volt)
    tmc.ask_and_print_float("Mean Square Root", ":MEASure:VRMS?", "", as_volt)
    print("")
    tmc.ask_and_print_float("Overshoot", ":MEASure:OVER?", "", as_volt)
    tmc.ask_and_print_float("Preshoot", ":MEASure:PRES?", "", as_volt)
    print("")
    tmc.ask_and_print_float("Frequency", ":MEASure:FREQuency?", "", as_hz)
    tmc.ask_and_print_float0("Rise time", ":MEASure:RISetime?", "", as_time)
    tmc.ask_and_print_float0("Fall time", ":MEASure:FALL?", "", as_time)
    tmc.ask_and_print_float("Period", ":MEASure:PER?", "", as_time)
    tmc.ask_and_print_float("Positive pulse width", ":MEASure:PWID?", "", as_time)
    tmc.ask_and_print_float("Negative pulse width", ":MEASure:NWID?", "", as_time)
    tmc.ask_and_print_float("Positive pulse duty cycle", ":MEASure:PDUT?", "")
    tmc.ask_and_print_float("Negative pulse duty cycle", ":MEASure:NDUT?", "")
    print_sep()
    print("")

tmc.do_and_close(blahblah)
