#!/usr/bin/python

from usbtmc import *

l = 30

print("")
print_sep()
ask_and_print_float("Maximum (peak)", ":MEASure:VMAX?", "", as_volt)
ask_and_print_float("Minimum (peak)", ":MEASure:VMIN?", "", as_volt)
ask_and_print_float("Peak-to-peak (Max - Min)", ":MEASure:VPP?", "", as_volt)
print("")
ask_and_print_float("Top (avg max)", ":MEASure:VTOP?", "", as_volt)
ask_and_print_float("Base (avg min)", ":MEASure:VBAS?", "", as_volt)
ask_and_print_float("Amplitude (Top - Base)", ":MEASure:VAMPlitude?", "", as_volt)
print("")
ask_and_print_float("Average", ":MEASure:VAV?", "", as_volt)
ask_and_print_float("Mean Square Root", ":MEASure:VRMS?", "", as_volt)
print("")
ask_and_print_float("Overshoot", ":MEASure:OVER?", "", as_volt)
ask_and_print_float("Preshoot", ":MEASure:PRES?", "", as_volt)
print("")
ask_and_print_float("Frequency", ":MEASure:FREQuency?", "", as_hz)
ask_and_print_float0("Rise time", ":MEASure:RISetime?", "", as_time)
ask_and_print_float0("Fall time", ":MEASure:FALL?", "", as_time)
ask_and_print_float("Period", ":MEASure:PER?", "", as_time)
ask_and_print_float("Positive pulse width", ":MEASure:PWID?", "", as_time)
ask_and_print_float("Negative pulse width", ":MEASure:NWID?", "", as_time)
ask_and_print_float("Positive pulse duty cycle", ":MEASure:PDUT?", "")
ask_and_print_float("Negative pulse duty cycle", ":MEASure:NDUT?", "")
print_sep()
print("")

scope.close()
