#!/usr/bin/python
# Copyright (c) 2017, Akshaal blahblahblah, GNU GPL blahblahblah

from akrigol import *

tmc = UsbTMC()

def blahblah():
    print("")
    print_sep()
    print(make_timestamp())
    print("")
    tmc.ask_and_print("Identifier", "*IDN?")
    print("")
    tmc.ask_and_print_float("Sampling rate", ":ACQuire:SAMPlingrate?", "", as_wtf)
    tmc.ask_and_print("Acquire type", ":ACQuire:TYPE?")
    tmc.ask_and_print("Acquire mode", ":ACQuire:MODE?")
    tmc.ask_and_print("Average acquisition time", ":ACQuire:AVERages?")
    print("")

    def chan_info(n):
        tmc.ask_and_print("Channel " + n + ": BW (bandwidth) Limit", ":CHANnel" + n + ":BWLimit?")
        tmc.ask_and_print("Channel " + n + ": Coupling", ":CHANnel" + n + ":Coupling?")
        tmc.ask_and_print("Channel " + n + ": Display", ":CHANnel" + n + ":Display?")
        tmc.ask_and_print("Channel " + n + ": Invert", ":CHANnel" + n + ":Invert?")
        tmc.ask_and_print_float("Channel " + n + ": Vertical offset", ":CHANnel" + n + ":Offset?", "", as_volt)
        tmc.ask_and_print_float("Channel " + n + ": Probe", ":CHANnel" + n + ":Probe?", " X")
        tmc.ask_and_print_float("Channel " + n + ": Scale", ":CHANnel" + n + ":Scale?", "", as_volt)
        tmc.ask_and_print("Channel " + n + ": Filter", ":CHANnel" + n + ":Filter?")
        tmc.ask_and_print_float("Channel " + n + ": Memory depth", ":CHANnel" + n + ":MEMoryDepth?", "", as_wtf)
        tmc.ask_and_print("Channel " + n + ": Vert scale adjust-mode", ":CHANnel" + n + ":VERNier?")

    chan_info("1")
    print("")
    chan_info("2")

    print("")
    tmc.ask_and_print("Timebase mode", ":TIMebase:MODE?")
    tmc.ask_and_print_float("Timebase offset", ":TIMebase:OFFSet?", "", as_time)
    tmc.ask_and_print_float("Timebase scale", ":TIMebase:Scale?", "", as_time)
    tmc.ask_and_print("Timebase format", ":TIMebase:Format?")

    print_sep()
    print("")

tmc.do_and_close(blahblah)
