#!/usr/bin/env python
# Copyright (c) 2017, Akshaal blahblahblah, GNU GPL blahblahblah

import wave
import akrigol
import numpy

# Read previously serialized 'scope' object
scp = akrigol.deserialize("scope")

# Write wav
def mkfilen(pref):
    return"out/channel1-" + pref + akrigol.make_timestamp(scp.retrieval_date)
outwavf = mkfilen("") + ".wav"

rawdata = numpy.getbuffer(scp.active_channels[0].raw_points)

print("Writing: " +  outwavf)
wav_file = wave.open(outwavf, "w")
data_size = len(rawdata)
sample_rate = scp.active_channels[0].sample_rate
nchannels = 1
sampwidth = 1
comptype = "NONE"
compname = "not compressed"

wav_file.setparams((nchannels, sampwidth, sample_rate, data_size, comptype, compname))
wav_file.writeframes(rawdata)
wav_file.close()

# Write spectrogram
def write_sp(kind):
    outspecf = mkfilen("spektr-" + kind + "-") + ".png"
    print("Writing " + outspecf)
    akrigol.call(["sox", outwavf, "-n", "spectrogram", "-w", kind, "-o", outspecf])

write_sp("hann")
write_sp("hamming")
write_sp("bartlett")
write_sp("rectangular")
write_sp("kaiser")
