#!/usr/bin/env python
# Copyright (c) 2017, Akshaal blahblahblah, GNU GPL blahblahblah

import wave
import akrigol
import numpy

# Read previously serialized 'scope' object
scp = akrigol.deserialize("scope")

# Write wav
outwavfbase = "out/channel1-" + akrigol.make_timestamp(scp.retrieval_date)
outwavf = outwavfbase + ".wav"

rawdata = numpy.getbuffer(scp.active_channels[0].raw_points)

print("Writing: " +  outwavf)
wav_file = wave.open(outwavf, "w")
data_size = len(rawdata)
sample_rate = scp.active_channels[0].sample_rate
nchannels = 1
sampwidth = 1
comptype = "NONE"
compname = "not compressed"

wav_file.setparams((nchannels, sampwidth, sample_rate, data_size, comptype, compname))
wav_file.writeframes(rawdata)
wav_file.close()

# Write spectrogram

outspecf = outwavfbase + "-spectr.png"
akrigol.call(["sox", outwavf, "-n", "spectrogram", "-o", outspecf])
